# Generated by Django 5.0.14 on 2025-08-24 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('homework', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='graded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradecomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradecomment',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='homework.grade'),
        ),
        migrations.AddField(
            model_name='homeworkassignment',
            name='lecture',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homework_assignment', to='courses.lecture'),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='homework.homeworkassignment'),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grade',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='homework.homeworksubmission'),
        ),
        migrations.AlterUniqueTogether(
            name='homeworksubmission',
            unique_together={('assignment', 'student')},
        ),
    ]
